From 0bcd681b0a83d8a6500def6b594aec3cb07d5a47 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Ond=C5=99ej=20Nov=C3=BD?= <onovy@debian.org>
Date: Fri, 23 Sep 2016 13:52:43 +0200
Subject: Fixed bytes unit tests fail on Python 3.5

Forwarded: https://github.com/PythonCharmers/python-future/pull/243
---
 tests/test_future/test_bytes.py | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)

--- a/tests/test_future/test_bytes.py
+++ b/tests/test_future/test_bytes.py
@@ -7,6 +7,8 @@ from __future__ import absolute_import,
 from future.builtins import *
 from future import utils
 
+import sys
+
 from numbers import Integral
 from future.tests.base import unittest, expectedFailurePY2
 
